services:
  - type: web
    name: market2farm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
