server {
    listen 80;
    server_name market2farm.com;
    location / {
        proxy_pass http://unix:/var/run/market2farm.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /static {
        alias /path/to/static;
    }
}